# Generated by Django 3.2 on 2021-04-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_email_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default='Default', max_length=255, unique=True, verbose_name='Config Name')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('fail_silently', models.BooleanField(default=False)),
                ('max_attempts', models.IntegerField(default=20)),
                ('default_attempts_wait', models.IntegerField(default=60)),
                ('default_attempts_wait_multiplier', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Email Config',
                'verbose_name_plural': 'Email Configs',
            },
        ),
    ]
