# Generated by Django 3.2 on 2021-04-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_email_manager', '0002_emailconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfig',
            name='active',
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='default',
            field=models.BooleanField(default=True, verbose_name='default'),
        ),
    ]
