# Generated by Django 3.2 on 2021-04-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_email_manager', '0003_auto_20210426_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='backend',
            field=models.CharField(choices=[('SMTP', 'SMTP Backend'), ('CONS', 'Console Backend')], default='SMTP', max_length=5),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='template_email_manager.emailconfig'),
            preserve_default=False,
        ),
    ]
