# Generated by Django 3.2 on 2021-04-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_email_manager', '0006_alter_htmltemplate_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueue',
            name='context_items',
            field=models.ManyToManyField(blank=True, to='template_email_manager.ContextItem'),
        ),
    ]
