# Generated by Django 3.2 on 2021-04-29 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('template_email_manager', '0007_alter_emailqueue_context_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailqueue',
            name='error_log',
        ),
        migrations.CreateModel(
            name='EmailQueueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CRE', 'Creating'), ('REA', 'Ready'), ('INP', 'In Progress'), ('SEN', 'Sent'), ('FAI', 'Send Failed'), ('USC', 'User Canceled'), ('MAC', 'Canceled for Maximum number of sending attempts')], max_length=5)),
                ('send_attempt', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('log_info', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='template_email_manager.emailqueue')),
            ],
            options={
                'verbose_name': 'E-mail Queue Log',
                'verbose_name_plural': 'E-mail Queue Logs',
            },
        ),
    ]
